# Generated by Django 4.1 on 2023-02-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0015_rename_userlogs_vendorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryParentId', models.IntegerField(blank=True, default=0, null=True)),
                ('categoryDescription', models.TextField()),
                ('categoryStatus', models.IntegerField(blank=True, default=0, null=True)),
                ('categorySortOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('categoryImgage', models.ImageField(upload_to='static/images/Category/')),
                ('categoryCreatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoryUpdatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.vendorlog')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=50)),
                ('productDesc', models.TextField()),
                ('productThumb', models.ImageField(upload_to='static/images/product/')),
                ('productPrice', models.FloatField()),
                ('productQty', models.IntegerField(default=0)),
                ('Unlimited', models.IntegerField(default=0)),
                ('productStatus', models.IntegerField(default=0)),
                ('preparationTime', models.DurationField(blank=True, null=True)),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.vendorlog')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
