# Generated by Django 4.1 on 2023-02-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0015_rename_userlogs_vendorlog'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('SKU', models.CharField(max_length=50)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.vendorlog')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifierName', models.CharField(max_length=100)),
                ('modifierSKU', models.CharField(max_length=50)),
                ('modifierPrice', models.FloatField(blank=True, null=True)),
                ('modifierStatus', models.IntegerField(default=0)),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.vendorlog')),
            ],
        ),
    ]
