# Generated by Django 4.1 on 2023-02-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modifiergroup_modifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modifier')),
                ('modifierGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modifiergroup')),
            ],
        ),
    ]
