# Generated by Django 4.1 on 2023-02-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modifier_modifierimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryParentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
