# Generated by Django 4.1 on 2023-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_categoryparentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='modifierDesc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='modifierQty',
            field=models.IntegerField(default=0),
        ),
    ]
