# Generated by Django 4.1 on 2023-03-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
    ]
