# Generated by Django 4.1 on 2023-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_modifier_modifierqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='modifierQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='modifierStatus',
            field=models.BooleanField(default=False),
        ),
    ]
