# Generated by Django 4.1 on 2023-02-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryDesc', models.TextField()),
                ('categoryImg', models.ImageField(upload_to='static/img/Category/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFirstName', models.CharField(default='', max_length=50)),
                ('customerLastName', models.CharField(default='', max_length=50)),
                ('customerUsername', models.CharField(max_length=100)),
                ('customerPassword', models.CharField(max_length=100)),
                ('customerEmail', models.CharField(max_length=254)),
                ('customerNumber', models.IntegerField(default=0)),
                ('customerAddress', models.TextField()),
                ('customerImg', models.ImageField(blank=True, default='static/img/default/customer/default_user.png', upload_to='static/img/customer/')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountCode', models.CharField(max_length=50)),
                ('discountValue', models.FloatField()),
                ('discountDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodName', models.CharField(max_length=50)),
                ('methodDesc', models.CharField(max_length=50)),
                ('getway', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('SKU', models.CharField(max_length=50)),
                ('productPrice', models.FloatField()),
                ('productDesc', models.TextField()),
                ('productStock', models.IntegerField()),
                ('productImg', models.ImageField(upload_to='static/img/product/')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.FloatField()),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartContain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woostore.customer'),
        ),
    ]
