# Generated by Django 4.1 on 2023-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woostore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryImg',
            field=models.ImageField(upload_to='static/images/Category/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerImg',
            field=models.ImageField(blank=True, default='static/img/default/customer/default_user.png', upload_to='static/images/customer/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImg',
            field=models.ImageField(upload_to='static/images/product/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='static/images/product_images/'),
        ),
    ]
