# Generated by Django 4.1 on 2023-02-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.modules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.logs')),
            ],
        ),
    ]
