# Generated by Django 4.1 on 2023-02-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_modules_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.modules'),
        ),
    ]
