# Generated by Django 4.1 on 2023-02-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0005_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='user',
        ),
        migrations.AddField(
            model_name='permissions',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='useradmin.logs'),
        ),
    ]
