# Generated by Django 4.1 on 2023-02-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0006_remove_permissions_user_permissions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.logs', unique=True),
        ),
    ]
