# Generated by Django 4.1 on 2023-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0007_alter_permissions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, to='useradmin.modules'),
        ),
    ]
