# Generated by Django 4.1 on 2023-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0009_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='useradmin.group'),
        ),
    ]
