# Generated by Django 4.1.6 on 2023-02-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0010_logs_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group',
            new_name='PermissionGroup',
        ),
        migrations.RenameModel(
            old_name='logs',
            new_name='UserLogs',
        ),
    ]
