# Generated by Django 4.1.6 on 2023-02-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0011_rename_group_permissiongroup_rename_logs_userlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogs',
            old_name='pas',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userlogs',
            old_name='uname',
            new_name='userName',
        ),
    ]
