# Generated by Django 4.1.6 on 2023-02-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0012_rename_pas_userlogs_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='user',
            new_name='userName',
        ),
    ]
