# Generated by Django 4.1.6 on 2023-02-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0013_rename_user_permissions_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='userName',
            new_name='user',
        ),
    ]
