# Generated by Django 4.1 on 2023-02-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0014_rename_username_permissions_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogs',
            new_name='VendorLog',
        ),
    ]
