# Generated by Django 4.1 on 2023-03-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0015_rename_userlogs_vendorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('shippingAddress', models.TextField()),
                ('billingAddress', models.TextField()),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.vendorlog')),
            ],
        ),
    ]
