# Generated by Django 4.1 on 2023-03-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_rename_discount_kioskdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdiscount',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kioskdiscount',
            name='discountCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kioskdiscount',
            name='discountCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kioskdiscount',
            name='discountDesc',
            field=models.TextField(default=''),
        ),
    ]
